### ISSUE TITLE
May not work with Node v7 or npm v4

### ISSUE THREAD

**Issue by wearhere** [mixmaxhq/install-files#14]
Moving from https://github.com/mixmaxhq/eb-fix-npm/issues/11, a stacktrace from @ Ewg777:

```
node_modules\install-files\src\hostPackageDir.js:12
var pathComponents = file.split(path.sep);
^
TypeError: Cannot read property 'split' of undefined
at hostPackageDir (C:\Users\user\untitled\node_modules\install-files\src\hostPackageDir.js:12:28)
at installFiles (C:\Users\user\untitled\node_modules\install-files\src\index.js:45:35)
at Object. (C:\Users\user\untitled\node_modules\install-files\bin\install-files.js:16:1)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.runMain (module.js:605:10)
at run (bootstrap_node.js:427:7)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "eb-fix-npm" "--save-dev"
npm ERR! node v7.10.0
npm ERR! npm v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! eb-fix-npm@1.2.5 install: install-files source
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eb-fix-npm@1.2.5 install script 'install-files source'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eb-fix-npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! install-files source
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs eb-fix-npm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls eb-fix-npm
npm ERR! There is likely additional logging output above.
```

Note that `eb-fix-npm` uses `install-files^1.0.0`. I would not expect this issue to be fixed by 2.0.0 however.

This error indicates that `process.env._` is undefined [here](https://github.com/mixmaxhq/install-files/blob/67ceaf6b3ce60936bacbc3757b60c2337d984c88/src/index.js#L45) for some reason.

Mixmax has not seen this issue yet. We use Yarn 0.24.6 and Node 8.9.3.

**Comment by skeggse** [comment]
That environment variable looks to be [bash-specific](https://unix.stackexchange.com/a/293000) fyi. Moving to using `PWD` should be far more reliable.

**Comment by wearhere** [comment]
Oh interesting. I think [this](https://github.com/mixmaxhq/install-files/blob/4959914b21e5562c285e5425e52f6695d6cb89aa/src/index.js#L51) will still throw though… we should probably only try to use `process.env._` if we need it, in the first or third branches [here](https://github.com/mixmaxhq/install-files/blob/4959914b21e5562c285e5425e52f6695d6cb89aa/src/index.js#L70).
